version: '3.8'
services:
  frontend:
    environment:
      REACT_APP_ADMIN_URL: http://localhost:8000
    image: pyms_reactapp:0.1
    build:
      context: . 
      dockerfile: Dockerfile
    command: 'npm start'
    ports:
      - 3000:3000
    