###### ADMIN APP #####
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /    
spec:
  defaultBackend:
    service:
      name: react-app
      port:
        number: 3002 
  ingressClassName: nginx

  rules:

  - host: admin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-app
            port:
              number: 3000
              
  - host: main.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: main-app
            port:
              number: 3001
  
  - host: rcrud.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-app
            port:
              number: 3002


