apiVersion: v1
kind: Service
metadata:
  name: main-app
spec:
  selector:
    app: main-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: main-app-db
spec:  
  selector:
    app: main-app-db
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30020
    protocol: TCP
  type: NodePort
  # type: ClusterIP

##################################################################################

## Deployments
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-db
spec:
  selector:
    matchLabels:
      app: main-app-db
  template:
    metadata:
      labels:
        app: main-app-db
    spec:
      containers:
      - name: main-app-db
        image: pyms_main_mysql:0.1    
              
        env:
        - name: MYSQL_DATABASE
          value: main        
        - name: MYSQL_PASSWORD
          value: root  
        - name: MYSQL_ROOT_PASSWORD
          value: root        
        
        resources:
        ports:
          - containerPort: 3306            
---

apiVersion: batch/v1
kind: Job
metadata:
  name: main-sql-job
spec:
  template:
    spec:
      containers:
      - name: myjob
        image: pyms_main_backend:0.1
        command: ["sh","-c"]        
        args: ["python manage.py db init; echo INIT DONE && python manage.py db migrate && echo MIGRATE DONE && python manage.py db upgrade && echo UPGRADE DONE"]        
        env:
          - name: ADMIN_URL
            value: http://admin-app.default.svc.cluster.local:8000
          - name: QUEUE_URL
            value: amqps://snwftsci:eiBfAIXrTH3uyenftpshNJwhGBFIfDya@rattlesnake.rmq.cloudamqp.com/snwftsci
          - name: DB_URI
            value: mysql://root:root@main-app-db.default.svc.cluster.local/main
      restartPolicy: OnFailure
  backoffLimit: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
spec:
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      restartPolicy: Always
      containers:
      - name: main-app-backend
        image: pyms_main_backend:0.1
          
        env:
        - name: ADMIN_URL
          value: http://admin-app.default.svc.cluster.local:8000
        - name: QUEUE_URL
          value: amqps://snwftsci:eiBfAIXrTH3uyenftpshNJwhGBFIfDya@rattlesnake.rmq.cloudamqp.com/snwftsci
        - name: DB_URI
          value: mysql://root:root@main-app-db.default.svc.cluster.local/main
        command: ["python", "main.py"]
        resources:
        
        ports:
        - containerPort: 8000


--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-queue
spec:
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main-app-queue
        image: pyms_main_queue:0.1      
        env:
        - name: ADMIN_URL
          value: http://admin-app.default.svc.cluster.local:8000
        - name: QUEUE_URL
          value: amqps://snwftsci:eiBfAIXrTH3uyenftpshNJwhGBFIfDya@rattlesnake.rmq.cloudamqp.com/snwftsci
        - name: DB_URI
          value: mysql://root:root@main-app-db.default.svc.cluster.local/main
        command: ["python", "consumer.py"]
        resources: