version: '3.8'
services:
  backend:
    image: pyms_admin_backend:0.1
    build:
      context: . 
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    environment:    
      QUEUE_URL: amqps://snwftsci:eiBfAIXrTH3uyenftpshNJwhGBFIfDya@rattlesnake.rmq.cloudamqp.com/snwftsci
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    image: pyms_admin_queue:0.1
    build:
      context: . 
      dockerfile: Dockerfile
    command: 'python consumer.py'
    environment:    
      QUEUE_URL: amqps://snwftsci:eiBfAIXrTH3uyenftpshNJwhGBFIfDya@rattlesnake.rmq.cloudamqp.com/snwftsci
    depends_on:
      - db
  
  db: 
    image: pyms_admin_mysql:0.1
    build:
      context: ../db/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #   - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306


  